project:
  name: quickstart-aws-industrial-machine-connectivity
  owner: quickstart@amazon.com
  package_lambda: false
  s3_bucket: ''
  shorten_stack_name: true
  parameters:
      CreateAdditionalPrivateSubnets: 'true'
      CreatePrivateSubnets: 'true'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
      QSS3BucketName: $[taskcat_autobucket] # will need to follow 'virtual deployment' instructions in user guide 
      QSS3KeyPrefix: quickstart-aws-industrial-machine-connectivity/ # will need to follow 'virtual deployment' instructions in user guide 
      QSS3BucketRegion: $[taskcat_current_region]
      UserPublicIP: '205.251.233.48' # change
      EC2KeyPairName: sshvans # change
  template: templates/IMC-master.template.yaml

tests:
  VOption1:
    parameters:
      DeploymentType: Virtual
      DeploymentOption: Option1
    regions:
      - us-east-1
    
  VOption2a:
    parameters:
      DeploymentType: Virtual
      DeploymentOption: Option2a
    regions:
      - us-west-2

  VOption2b:
    parameters:
      DeploymentType: Virtual
      DeploymentOption: Option2b
    regions:
      - eu-west-1

  POption1:
    parameters:
      DeploymentType: Physical
      DeploymentOption: Option1
    regions:
      - us-east-1

  POption2a:
    parameters:
      DeploymentType: Physical
      DeploymentOption: Option2a
    regions:
      - us-west-2

  PGOption2b:
    parameters:
      DeploymentType: Physical
      DeploymentOption: Option2b
    regions:
      - eu-west-1

