project:
  name: imc-quickstart
  owner: shahan@tensoriot.com # change
  package_lambda: false
  s3_bucket: ''
  shorten_stack_name: true
tests:
  Option1:
    parameters:
      CreateAdditionalPrivateSubnets: 'true'
      CreatePrivateSubnets: 'true'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
      QSS3BucketName: submodule-test-quickstart # will need to follow 'virtual deployment' instructions in user guide 
      QSS3KeyPrefix: quickstart/ # will need to follow 'virtual deployment' instructions in user guide 
      # UserPublicIP: 'x.x.x.x' # change
      UserPublicIP: '47.232.192.250'
      EC2KeyPairName: SiteWiseTest # change
      DeploymentType: Virtual
      DeploymentOption: Option1
    regions:
      - us-east-1
      - us-west-2
      - eu-west-1
    s3_bucket: ''
    template: templates/IMC-master.template.yaml
  Option2a:
    parameters:
      CreateAdditionalPrivateSubnets: 'true'
      CreatePrivateSubnets: 'true'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
      QSS3BucketName: submodule-test-quickstart # will need to follow 'virtual deployment' instructions in user guide 
      QSS3KeyPrefix: quickstart/ # will need to follow 'virtual deployment' instructions in user guide 
      # UserPublicIP: 'x.x.x.x' # change
      UserPublicIP: '47.232.192.250'
      EC2KeyPairName: SiteWiseTest # change
      DeploymentType: Virtual
      DeploymentOption: Option2a
    regions:
      - us-east-1
      - us-west-2
      - eu-west-1
    s3_bucket: ''
    template: templates/IMC-master.template.yaml
  Option2b:
    parameters:
      CreateAdditionalPrivateSubnets: 'true'
      CreatePrivateSubnets: 'true'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
      QSS3BucketName: submodule-test-quickstart # will need to follow 'virtual deployment' instructions in user guide 
      QSS3KeyPrefix: quickstart/ # will need to follow 'virtual deployment' instructions in user guide 
      # UserPublicIP: 'x.x.x.x' # change
      UserPublicIP: '47.232.192.250'
      EC2KeyPairName: SiteWiseTest # change
      DeploymentType: Virtual
      DeploymentOption: Option2b
    regions:
      - us-east-1
      - us-west-2
      - eu-west-1
    s3_bucket: ''
    template: templates/IMC-master.template.yaml