project:
  name: quickstart-aws-industrial-machine-connectivity
  owner: quickstart@amazon.com
  package_lambda: false
  shorten_stack_name: true
  parameters:
      QSS3BucketName: $[taskcat_autobucket] # will need to follow 'virtual deployment' instructions in user guide 
      QSS3KeyPrefix: quickstart-aws-industrial-machine-connectivity/ # will need to follow 'virtual deployment' instructions in user guide 
      QSS3BucketRegion: $[taskcat_current_region]
  template: templates/IMC-main.template.yaml

tests:
  ICLTestVirtual:
    parameters:
      ModelingVendorType: "Asset Model Converter"
      AMCDriver: "IgnitionCirrusLink"
      DeploymentType: "Virtual"
      EC2KeyPairName: OVERRIDE
      EdgeDeviceID: Virtual
      GreengrassInstanceType: t3.small
      IgnitionInstanceType: t3.large
      PublicSubnet1CIDR: 10.0.128.0/20
      SitewiseMonitorEmail: OVERRIDE
      UserPublicIP: OVERRIDE
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
      UnifyUsername: OVERRIDE
      UnifyPassword: OVERRIDE
    regions:
      - eu-central-1
  
  ICLTestPhysical:
    parameters:
      ModelingVendorType: "Asset Model Converter"
      AMCDriver: "IgnitionCirrusLink"
      DeploymentType: "Physical"
      EC2KeyPairName: OVERRIDE
      EdgeDeviceID: Physical
      GreengrassInstanceType: t3.small
      IgnitionInstanceType: t3.large
      PublicSubnet1CIDR: 10.0.128.0/20
      SitewiseMonitorEmail: OVERRIDE
      UserPublicIP: OVERRIDE
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
      UnifyUsername: OVERRIDE
      UnifyPassword: OVERRIDE
    regions:
      - eu-central-1
  
  # ElementUnify:
  #   parameters:
  #     ModelingVendorType: "Element Unify"
  #     AMCDriver: "Element Unify"
  #     DeploymentType: "Physical"
  #     EC2KeyPairName: OVERRIDE
  #     EdgeDeviceID: Virtual
  #     GreengrassInstanceType: t3.small
  #     IgnitionInstanceType: t3.large
  #     PublicSubnet1CIDR: 10.0.128.0/20
  #     SitewiseMonitorEmail: OVERRIDE
  #     UserPublicIP: OVERRIDE
  #     VPCCIDR: 10.0.0.0/16
  #     VPCTenancy: default
  #     UnifyUsername: OVERRIDE
  #     UnifyPassword: OVERRIDE
  #     UnifyHostname: https://app001-aws.elementanalytics.com/
  #     UnifyOrgId: OVERRIDE
  #   regions:
  #     - eu-central-1