AWSTemplateFormatVersion: 2010-09-09
Description: IMC Quickstart
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
          - VPCCIDR
          - PublicSubnet1CIDR
          - VPCTenancy
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
      - Label:
          default: Edge Deployment Configuration
        Parameters:
          - EdgeDeviceID
          - DeploymentType
          - DeploymentOption
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - EC2KeyPairName
          - GreengrassInstanceType
          - IgnitionInstanceType
          - AMCDriver
          - UserPublicIP          
    ParameterLabels:
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      VPCTenancy:
        default: VPC tenancy
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      VPCCIDR:
        default: VPC CIDR
      EC2KeyPairName:
        default: SSH Key Name
      EdgeDeviceID:
        default: Name for the edge device 
      DeploymentType:
        default: Type of deployment (virtual or physical)
      DeploymentOption:
        default: Deployment flows
      GreengrassInstanceType:
        default: Greengrass EC2 instance type
      IgnitionInstanceType:
        default: Ignition EC2 instance type
      AMCDriver:
        default: AssetModelConverter driver
      UserPublicIP:
        default: Input your public IP address so that you have SSH access to EC2 instances        

  cfn-lint: { config: { ignore_checks: [E9007] } }
Parameters:
  UserPublicIP:
    Type: String
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
  AMCDriver:
    Type: String
    Default: IgnitionCirrusLink
    AllowedValues:
      - IgnitionCirrusLink
      - IgnitionFileExport
      - KepwareFileExport
    Description: Choose the driver that the AssetModelConverter uses to translate hierarchy data.   
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR Block for the public DMZ subnet 1 located in Availability Zone 1.
    Type: String
  VPCTenancy:
    AllowedValues:
      - default
      - dedicated
    Default: default
    Description: The allowed tenancy of instances launched into the VPC.
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^([0-9a-zA-Z-.]+/)*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), dots (.) and forward slash (/). The prefix should end with a forward slash (/).
    Description:       S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), dots
      (.) and forward slash (/) and it should end with a forward slash (/).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC.
    Type: String
  EdgeDeviceID:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Edge Device ID name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Type: String
    Default: Virtual
    Description: Name for the edge device. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
  EC2KeyPairName:
    Description: Name of an existing EC2 key pair. All instances will launch with
      this key pair.
    Type: AWS::EC2::KeyPair::KeyName
    Default: keypairtest
  DeploymentType:
    AllowedValues:
      - Virtual
      - Physical
    ConstraintDescription: Must contain valid deployment type
    Description: Type of edge deployment
    Type: String
    Default: Virtual
  DeploymentOption:
    AllowedValues:
      - Option1
      - Option2a
      - Option2b
    ConstraintDescription: Must be a valid deployment option selection 
    Description: They further defined deployment type
      --- Option1 (or OPC-UA Path via SiteWise)
      --- Option 2a (MQTT Ignition --> Iot Core)
      --- Option 2b (MQTT Ignition --> Greengrass --> Iot Core)
    Type: String
    Default: Option1 
  GreengrassInstanceType:
    Description: Amazon EC2 instance type for the Greengrass EC2 instances.
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.small
      - t3.medium
  IgnitionInstanceType:
    Description: Amazon EC2 instance type for the Ignition EC2 instances.
    Type: String
    Default: t3.large
    AllowedValues:
      - t3.large
      - t3.xlarge
Conditions:
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - 'aws-quickstart'
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.amazonaws.com/${QSS3KeyPrefix}templates/vpc.template.yaml
        - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub 'aws-quickstart-${AWS::Region}'
            - !Ref 'QSS3BucketName'
          S3Region: !If
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref 'QSS3BucketRegion'
      Parameters:
        AvailabilityZones: !Sub '${AWS::Region}a'
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        VPCCIDR: !Ref VPCCIDR
        VPCTenancy: !Ref VPCTenancy
  IMCWorkloadStack:
    DependsOn:
      - VPCStack
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.amazonaws.com/${QSS3KeyPrefix}templates/IMC-workload.template.yaml
        - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub 'aws-quickstart-${AWS::Region}'
            - !Ref 'QSS3BucketName'
          S3Region: !If
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref 'QSS3BucketRegion'
      Parameters:
        EC2Subnet:
          Fn::GetAtt: [VPCStack, Outputs.PublicSubnet1ID]        
        QSS3BucketRegion: !Ref QSS3BucketRegion
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        VpcId:
          Fn::GetAtt: [VPCStack, Outputs.MYVPCID]        
        EdgeDeviceID: !Ref EdgeDeviceID
        DeploymentType: !Ref DeploymentType
        DeploymentOption: !Ref DeploymentOption
        EC2KeyPairName: !Ref EC2KeyPairName
        GreengrassInstanceType: !Ref GreengrassInstanceType
        IgnitionInstanceType: !Ref IgnitionInstanceType
        AMCDriver: !Ref AMCDriver
        UserPublicIP: !Ref UserPublicIP